### ISSUE TITLE
hang if unclosed braces in input

### ISSUE THREAD

**Issue by ha7ilm** [Calysto/octave_kernel#149]
If accidentally there are any unclosed braces in the input, then:
- no error message is printed,
- I need to wait approx 30 seconds after interrupting the kernel to be able to use it again,
- if then I run code in another cell, the kernel thinks it's a continuation of the code in the previous cell.

To reproduce:

![image](https://user-images.githubusercontent.com/5903408/56796146-36d2de80-6812-11e9-85bc-ecf272206610.png)

...and then try to evaluate anything else in another cell.

**Comment by blink1073** [comment]
Thanks for the report, @ha7ilm!  This is fixed in 0.29.1:

![image](https://user-images.githubusercontent.com/2096628/57011961-c5a47a00-6bc9-11e9-8955-3c49bf425128.png)

**Comment by ha7ilm** [comment]
@blink1073 Thank you for the fix and for working on Octave kernel! It's very useful to me.

**Comment by ha7ilm** [comment]
Well, I tried the 0.29.1 release, and it still hung.

![image](https://user-images.githubusercontent.com/5903408/57013887-edb5cc80-6c0d-11e9-9163-63cbec13e480.png)

I get this in the terminal:

```[D 12:36:53.177 NotebookApp] activity on 5ddd9732-9c04-45fe-a94c-08f2ae52e046: execute_input
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcfl/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/pcfl/.local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/pcfl/.local/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pcfl/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.6/dist-packages/metakernel/_metakernel.py", line 357, in do_execute
    retval = self.do_execute_direct(code)
  File "/usr/local/lib/python3.6/dist-packages/octave_kernel/kernel.py", line 101, in do_execute_direct
    val = ProcessMetaKernel.do_execute_direct(self, code, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/process_metakernel.py", line 78, in do_execute_direct
    stdin_handler=self.raw_input)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/replwrap.py", line 175, in run_command
    self.interrupt()
  File "/usr/local/lib/python3.6/dist-packages/octave_kernel/kernel.py", line 383, in _interrupt
    return REPLWrapper.interrupt(self.repl)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/replwrap.py", line 192, in interrupt
    self._expect_prompt(timeout=-1)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/replwrap.py", line 129, in _expect_prompt
    pos = self.child.expect(expects, timeout=timeout)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f3170940fd0>
command: /usr/bin/octave-cli
args: [b'/usr/bin/octave-cli', b'--interactive', b'--quiet', b'--no-init-file']
buffer (last 100 chars): ''

after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 26320
child_fd: 53
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('PEXPECT_PROMPT>')
    1: re.compile('PEXPECT_PROMPT_')
    2: re.compile('\\A.+?__stdin_prompt>|debug> ')
    3: re.compile('\r\n')
```

Package versions:
```
jupyter                            1.0.0      
jupyter-client                     5.2.3      
jupyter-console                    5.2.0      
jupyter-core                       4.4.0
octave-kernel                      0.29.1 
```
OS: `Ubuntu 18.10`

**Comment by blink1073** [comment]
Do you have metakernel 0.21.2?

**Comment by ha7ilm** [comment]
I had an older version of `metakernel`, so I've just upgraded (and restarted `jupyter` of course), but it didn't solve it.

**Comment by blink1073** [comment]
Can you post the new traceback please?

**Comment by ha7ilm** [comment]
```
_input
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcfl/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/pcfl/.local/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/pcfl/.local/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/pcfl/.local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/usr/local/lib/python3.6/dist-packages/metakernel/_metakernel.py", line 357, in do_execute
    retval = self.do_execute_direct(code)
  File "/usr/local/lib/python3.6/dist-packages/octave_kernel/kernel.py", line 101, in do_execute_direct
    val = ProcessMetaKernel.do_execute_direct(self, code, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/process_metakernel.py", line 78, in do_execute_direct
    stdin_handler=self.raw_input)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/replwrap.py", line 175, in run_command
    self.interrupt()
  File "/usr/local/lib/python3.6/dist-packages/octave_kernel/kernel.py", line 383, in _interrupt
    return REPLWrapper.interrupt(self.repl)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/replwrap.py", line 192, in interrupt
    self._expect_prompt(timeout=-1)
  File "/usr/local/lib/python3.6/dist-packages/metakernel/replwrap.py", line 129, in _expect_prompt
    pos = self.child.expect(expects, timeout=timeout)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/home/pcfl/.local/lib/python3.6/site-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fca64763898>
command: /usr/bin/octave-cli
args: [b'/usr/bin/octave-cli', b'--interactive', b'--quiet', b'--no-init-file']
buffer (last 100 chars): ''

after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 9367
child_fd: 53
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: None
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('PEXPECT_PROMPT>')
    1: re.compile('PEXPECT_PROMPT_')
    2: re.compile('\\A.+?__stdin_prompt>|debug> ')
    3: re.compile('\r\n')
```

**Comment by blink1073** [comment]
That still isn't the latest metakernel as far as I can tell.  Please try `pip install -U metakernel && pip list | grep metakernel` and make sure it is 0.21.2.

**Comment by ha7ilm** [comment]
Steven, 

Thank you very much for spotting that.
It looks like the `python2`-`python3` confusion happened to me again.
Mostly I still use `python2`, and didn't even have `pip3` installed.
Previously I upgraded `metakernel` and `octave-kernel` through `pip2`, but it looks like there was a different `metakernel` package on my system for `python3`. 
After installing `pip3` and upgrading these packages, now I'm getting the correct behaviour:

![image](https://user-images.githubusercontent.com/5903408/57089839-a874c600-6d05-11e9-965a-d664a31f22ad.png)

Thank you for your time and the fix.
