### ISSUE TITLE
Not working with the new windowed version of octave

### ISSUE THREAD

**Issue by amic-github** [Calysto/octave_kernel#15]
Since octave is now running in widowed mode, the kernel does not work anymore.

Changing the line
        `executable = os.environ.get('OCTAVE_EXECUTABLE', 'octave')`
and replacing `'octave'` by `'octave -W'` worked in my case, but I am not sure of what would be the correct way to do it.

**Comment by blink1073** [comment]
What version of Octave are you using and on what operating system?

**Comment by runical** [comment]
I'm getting the same problems:

OS: Arch Linux
Jupyter: 4.0.6
Octave: 4.0.0
Python-metakernel: 0.11.0
python-octave_kernel: 0.12.6

When I start a jupyter notebook with an octave kernel, octave is started using the new gui which was introduced in version 4.0.0 and will crash once you enter a command. The kernel was built against octave 4.0.0 if that matters. If you need more info, I'll be happy to help.

**Comment by blink1073** [comment]
Does the new version (3.3.2) fix your problem?

**Comment by runical** [comment]
I assume you mean oct2py 3.3.2? I installed it and the octave magic in ipython works just fine. The octave kernel in jupyter continues to crash though. When the kernel is started, a windowed version of octave is started and it will still crash. According to systemd, the process tree for jupyter with the octave kernel is:

/user.slice/user-1000.slice/user@1000.service/jupyter.service
           ├─7975 /usr/bin/python3 /usr/bin/jupyter-notebook --no-browser
           ├─8659 /usr/bin/python -m octave_kernel -f /run/user/1000/jupyter/kernel-0a49118d-6f93-4fff-a572-d5304ac8b34c.json
           ├─8667 /usr/sbin/bash
           ├─8668 /usr/sbin/octave
           └─8669 /usr/lib/octave/4.0.0/exec/x86_64-unknown-linux-gnu/octave-gui

As you can see, the gui is started and for some reason and octave crashes. I'll attach a log later today.

**Comment by blink1073** [comment]
Oh, ha, yes, I also released a

**Comment by blink1073** [comment]
Got mixed up, please try octave_kernel 0.12.7.

**Comment by runical** [comment]
Yeah, that solves the crashes. The only issue I can see now is that plots generate a black square instead of an actual image, but that might have to do with the fact that the windowing system is now disabled (-W disables the window system, including graphics).

**Comment by blink1073** [comment]
Whoops, how does 0.12.8 look?

**Comment by runical** [comment]
I'm afraid that doesn't fix it. I did find something that might be related though. When I use the ipython oct2py octave magic without any -f option, the resulting image is the same as when using the octave kernel. This black is fixed when appending '-f svg', so my guess is that there is an error when using png images.

**Comment by blink1073** [comment]
Care to try 0.12.9?

**Comment by runical** [comment]
Lovely, that works. The image is rendered as it should.

Thank you for your time.

**Comment by blink1073** [comment]
Awesome, thanks for beta testing with me.
